### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by bdellegrazie** [bdellegrazie/lualdap#3]
@devurandom / @jirutka

I noticed that both of you have made significant contributions to lualdap privately and via some pull requests here. Would either of you like to take over the maintenance of it permanently?

Unfortunately I'm no longer using Lua at all in my current work. I only took over it ages ago because I happened to need specific patches against it and I haven't really done anything with it at all.

I'm happy to hand over maintenance to either one of you if wish.

(@jirutka - I'm not ignoring your request for a release, I'd like to either include @devurandom's changes as well or hand over maintenance to one or both of you)

**Comment by devurandom** [comment]
Hi Brett!

Thanks for the offer! I would be willing to become the curator, if there are no objections from anyone.

In any case, it should be publicly communicated who sees themselves as the maintainer/curator of this code. The best way to do that would probably be to reactivate the LuaForge repository. Do you have access to it? If not, the Future Maintainer (e.g. me or @jirutka) should get in touch with them to reroot it, so that `luaforge/lualdap` is no longer dormant and a collaboration of multiple maintainers under that roof becomes possible.

Do you know how the hand-over on LuaRocks would work? Can everyone publish all packages, or is it necessary to hand-over access?

**Comment by bdellegrazie** [comment]
@devurandom / @jirutka:
At the time when I took over there were some efforts to get access to LuaForge to re-root lualdap. At that time they were unsuccessful. You could try again if you wish. I too wish luaforge was re-rooted but I don't know who owns it any more.

The owners of Luarocks granted me ownership of the lualdap rocks, hence how I was able to upload a new version. In order to transfer ownership to the new maintainer, just ensure you have a luarocks account, give me the ID and I'll instruct them to update ownership accordingly.

Once ownership is transferred, I'll update the repo here to publicise the maintainer as the new owner so that there is less confusion.

How does that sound?

**Comment by bdellegrazie** [comment]
@devurandom Since there's been no objection from @jirutka if you have a luarocks account, please let me know the username and I'll get the lualdap rock transferred over to you if you still desire it.
Thanks!

**Comment by devurandom** [comment]
Hi! I tried to get in touch with @keplerproject to see whether we could put the LuaLDAP repository under their umbrella. @hishamhm suggested to create a new @LuaLDAP GitHub organisation and put the repository there, which is what I just did [[1]]. You should already have received an email inviting you to participate.

@hishamhm will now adjust the owner of the [luarocks.org repository](https://luarocks.org/modules/bdellegrazie/lualdap) accordingly.

The next step will be to ask GitHub staff to re-wire the fork-relationships of the following repositories to point to [[1]] as their upstream:
* https://github.com/luaforge/lualdap
* https://github.com/bdellegrazie/lualdap
* https://github.com/jirutka/lualdap

Meanwhile y'all could already set your repository's URL to [[1]].

[1]: https://github.com/lualdap/lualdap

**Comment by hishamhm** [comment]
Rock ownership transferred to @devurandom in luarocks.org!

**Comment by devurandom** [comment]
@bdellegrazie GitHub staff asked whether you agree with your repository being re-rooted to lualdap/lualdap. Could you please mail the answer to support@github.com, referencing `59525477be725_242ae7efea9c08220f0@unicorn-757328757-8pftr.mail`?

**Comment by bdellegrazie** [comment]
@devurandom I thought I'd already done this but looking through my email I couldn't find the mail to support. Just in case I haven't I've emailed them again, apologies.
